name = "geminiapi"
main = "dist/worker.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./dist/client"

[build]
command = "pnpm install && pnpm run build"
watch_dir = "src"

# 移除 routes 配置，使用 workers_dev 代替
workers_dev = true

[env.production]
name = "geminiapi-prod"

[env.staging]
name = "geminiapi-staging" 
