name = "gemini"
main = "src/worker.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./dist"

[build]
command = "pnpm install && pnpm run build"
output_dir = "dist"

[env.production]
name = "gemini-prod"

[env.staging]
name = "gemini-staging" 
